"""Normalize recording-microphone metadata into the Qdrant runtime contract."""

from __future__ import annotations

import json
import re
import sys
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any


DATASET = "micro_thu_am_dien_thoai"
BASE_DIR = Path(__file__).resolve().parent
INPUT_FILE = BASE_DIR / "data" / f"{DATASET}_processed.json"
OUTPUT_FILE = BASE_DIR / "data" / f"{DATASET}_processed_vi.json"

# These columns were generated by the source-cleaning workbook. Several contain
# shifted or malformed values, so they are used only through guarded parsers and
# are not copied verbatim into the Qdrant payload.
LEGACY_DERIVED_FIELDS = {
    "bang_tan_min_ghz",
    "bang_tan_max_ghz",
    "tan_so_am_thanh_min_hz",
    "tan_so_am_thanh_max_hz",
    "tan_so_truyen_min_ghz",
    "tan_so_truyen_max_ghz",
    "dung_luong_pin_hop_sac_mah",
    "dung_luong_pin_bo_phat_mah",
    "dung_luong_pin_bo_thu_mah",
    "thoi_gian_bo_thu_min_gio",
    "thoi_gian_bo_thu_max_gio",
    "thoi_gian_bo_phat_min_gio",
    "thoi_gian_bo_phat_max_gio",
    "thoi_gian_su_dung_min_gio",
    "thoi_gian_su_dung_max_gio",
    "sac_day_bo_thu_phut",
    "thoi_gian_sac_bo_thu_phut",
    "sac_day_bo_phat_phut",
    "thoi_gian_sac_bo_phat_phut",
    "so_chu_ky_sac",
    "khoang_cach_truyen_m",
    "khoi_luong_bo_phan_min_g",
    "khoi_luong_bo_phan_max_g",
    "tong_khoi_luong_cac_bo_phan_g",
    "nhiet_do_bo_phat_min_c",
    "nhiet_do_bo_phat_max_c",
    "nhiet_do_bo_thu_min_c",
    "nhiet_do_bo_thu_max_c",
    "cong_suat_truyen_dbm",
    "toan_tu_cong_suat_truyen",
    "huong_thu_am_chuan",
    "spl_db",
    "kich_thuoc_chuan",
    "chieu_dai_lon_nhat_mm",
    "chieu_rong_lon_nhat_mm",
    "chieu_cao_lon_nhat_mm",
    "so_mic_phat",
    "so_mic_thu",
    "loai_san_pham_chuan",
    "nam_san_xuat_chuan",
    "gia_goc_vnd",
    "gia_khuyen_mai_vnd",
    "kiem_tra_gia",
    "phan_tram_giam_gia",
    "kiem_tra_du_lieu",
}

PRODUCT_TYPES = {
    "micro thu âm không dây": "wireless_recording",
    "micro podcast/livestream": "podcast_livestream",
}
FEATURE_PATTERNS = (
    ("noise_reduction", ("lọc tiếng ồn", "noise cancelling")),
    ("auto_connect", ("tự động kết nối",)),
    ("mute", ("ngắt micro", "tắt tiếng", "tap-to-mute")),
    ("voice_change", ("đổi giọng",)),
    ("magnetic_mount", ("gắn từ tính", "nam châm")),
    ("safety_track", ("safety track",)),
    ("touch_control", ("màn hình cảm ứng",)),
    ("audio_settings", ("bit depth", "sample rate")),
    ("shock_mount", ("chống sốc", "shock mount")),
    ("status_light", ("đèn led",)),
    ("digital_gain_limiter", ("digital gain limiter", "chống vỡ tiếng")),
)


def _clean(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, str):
        value = re.sub(r"\s+", " ", value).strip()
        return value or None
    return value


def _number(value: Any) -> float | None:
    if value is None or isinstance(value, bool):
        return None
    if isinstance(value, (int, float, Decimal)):
        return float(value)
    match = re.search(r"-?\d+(?:[.,]\d+)?", str(value))
    return float(match.group().replace(",", ".")) if match else None


def _positive_number(value: Any, *, maximum: float | None = None) -> float | None:
    number = _number(value)
    if number is None or number <= 0:
        return None
    if maximum is not None and number > maximum:
        return None
    return number


def _positive_integer(value: Any, *, maximum: int | None = None) -> int | None:
    number = _positive_number(value, maximum=maximum)
    return int(number) if number is not None and number.is_integer() else None


def parse_vnd(value: Any) -> int | None:
    if value is None or isinstance(value, bool):
        return None
    if isinstance(value, (int, float, Decimal)):
        parsed = Decimal(str(value))
        return int(parsed) if parsed > 0 else None
    text = re.sub(r"(?i)(vnd|₫|đ)", "", str(value)).strip().replace(" ", "")
    if not text:
        return None
    try:
        if re.fullmatch(r"\d+(?:\.0+)?", text.replace(",", "")):
            parsed = Decimal(text.replace(",", ""))
        else:
            parsed = Decimal(re.sub(r"[.,]", "", text))
    except InvalidOperation:
        return None
    return int(parsed) if parsed > 0 else None


def normalize_product_type(value: Any) -> str | None:
    return PRODUCT_TYPES.get(str(value or "").strip().casefold())


def normalize_compatibility(value: Any) -> list[str]:
    text = str(value or "").casefold()
    matches = (
        ("ipados", ("ipados",)),
        ("ios", ("ios", "iphone")),
        ("android", ("android",)),
        ("camera", ("camera",)),
        ("macos", ("macos",)),
        ("windows", ("windows",)),
        ("playstation", ("playstation",)),
    )
    return [tag for tag, markers in matches if any(marker in text for marker in markers)]


def normalize_connectors(value: Any) -> list[str]:
    text = str(value or "").casefold()
    if not text or text.strip() in {"không", "không có", "none"}:
        return []
    matches = (
        ("lightning", ("lightning",)),
        ("usb_c", ("type-c", "type c", "usb-c", "usb c")),
        ("3_5mm", ("3.5mm", "3.5 mm", "3,5mm", "3,5 mm", "aux in")),
        ("xlr", ("xlr",)),
        ("micro_usb", ("micro usb", "micro-usb")),
        ("aux_in", ("aux in",)),
    )
    return [tag for tag, markers in matches if any(marker in text for marker in markers)]


def normalize_features(value: Any) -> list[str]:
    text = str(value or "").casefold()
    return [
        tag
        for tag, markers in FEATURE_PATTERNS
        if any(marker in text for marker in markers)
    ]


def normalize_pickup_pattern(value: Any) -> str | None:
    text = str(value or "").casefold()
    if "omnidirectional" in text or "đa hướng" in text:
        return "omnidirectional"
    if "supercardioid" in text or "siêu hướng" in text:
        return "supercardioid"
    return None


def normalize_wireless_band(value: Any) -> str | None:
    text = str(value or "").casefold()
    if "2.4" in text or "2,4" in text:
        return "2_4_ghz"
    return None


def normalize_runtime(value: Any) -> tuple[float | None, float | None]:
    text = str(value or "").strip().casefold()
    if not text or text in {"không", "không có", "none"}:
        return None, None
    values = [
        float(number.replace(",", "."))
        for number in re.findall(r"\d+(?:[.,]\d+)?", text)
    ]
    values = [number for number in values if 0 < number <= 200]
    if not values:
        return None, None
    return min(values), max(values)


def normalize_transmission_range(value: Any) -> float | None:
    return _positive_number(value, maximum=5000)


def _count_from_accessories(value: Any, label: str) -> int | None:
    text = str(value or "").casefold()
    match = re.search(rf"\b(\d+)\s*(?:x\s*)?{re.escape(label)}\b", text)
    if not match:
        return None
    count = int(match.group(1))
    return count if 0 < count <= 16 else None


def _set_if_present(target: dict[str, Any], key: str, value: Any) -> None:
    if value is not None and value != []:
        target[key] = value


def normalize_metadata(metadata: dict[str, Any]) -> dict[str, Any]:
    """Add typed, filter-safe fields and discard unsafe derived columns."""
    normalized = {
        key: cleaned
        for key, value in metadata.items()
        if key not in LEGACY_DERIVED_FIELDS and (cleaned := _clean(value)) is not None
    }
    flags: list[str] = []
    source_warning = str(_clean(metadata.get("kiem_tra_du_lieu")) or "")
    if source_warning:
        flags.append(source_warning)

    brand = str(_clean(metadata.get("brand")) or "").strip()
    product_type = normalize_product_type(
        metadata.get("Loại sản phẩm") or metadata.get("loai_san_pham_chuan")
    )
    compatibility = normalize_compatibility(metadata.get("Tương thích"))
    connectors = normalize_connectors(metadata.get("Cổng tai nghe, headphone"))
    features = normalize_features(metadata.get("Tính năng cơ bản"))
    pickup_pattern = normalize_pickup_pattern(
        metadata.get("Hướng thu âm") or metadata.get("huong_thu_am_chuan")
    )
    wireless_band = normalize_wireless_band(
        metadata.get("Băng tần") or metadata.get("bang_tan_min_ghz")
    )
    runtime_min, runtime_max = normalize_runtime(metadata.get("Thời gian sử dụng"))
    transmission_range = normalize_transmission_range(metadata.get("Khoảng cách truyền"))
    accessories = metadata.get("Phụ kiện đi kèm")
    transmitter_count = _positive_integer(metadata.get("so_mic_phat"), maximum=16)
    receiver_count = _positive_integer(metadata.get("so_mic_thu"), maximum=16)
    transmitter_count = transmitter_count or _count_from_accessories(
        accessories, "mic phát"
    )
    receiver_count = receiver_count or _count_from_accessories(accessories, "mic thu")

    original_price = parse_vnd(metadata.get("giá gốc")) or parse_vnd(
        metadata.get("gia_goc_vnd")
    )
    promotional_price = parse_vnd(metadata.get("giá khuyến mãi")) or parse_vnd(
        metadata.get("gia_khuyen_mai_vnd")
    )

    if not product_type:
        flags.append("missing_product_type")
    if not compatibility:
        flags.append("missing_compatibility")
    if not connectors:
        flags.append("missing_connector")
    raw_runtime = str(metadata.get("Thời gian sử dụng") or "").strip().casefold()
    if raw_runtime and raw_runtime not in {"không", "không có", "none"} and runtime_min is None:
        flags.append("invalid_runtime")
    generated_runtime = _number(metadata.get("thoi_gian_su_dung_min_gio"))
    if generated_runtime is not None and generated_runtime < 0:
        flags.append("ignored_invalid_generated_runtime")

    _set_if_present(normalized, "brand", brand or None)
    _set_if_present(normalized, "brand_key", brand.casefold() or None)
    _set_if_present(normalized, "model_code", _clean(metadata.get("model_code")))
    _set_if_present(normalized, "product_type", product_type)
    _set_if_present(normalized, "original_price_vnd", original_price)
    _set_if_present(normalized, "promotional_price_vnd", promotional_price)
    _set_if_present(normalized, "compatibility_tags", compatibility)
    _set_if_present(normalized, "connector_tags", connectors)
    _set_if_present(normalized, "feature_tags", features)
    _set_if_present(normalized, "pickup_pattern", pickup_pattern)
    _set_if_present(normalized, "wireless_band", wireless_band)
    _set_if_present(normalized, "transmitter_count", transmitter_count)
    _set_if_present(normalized, "receiver_count", receiver_count)
    _set_if_present(normalized, "runtime_min_hours", runtime_min)
    _set_if_present(normalized, "runtime_max_hours", runtime_max)
    _set_if_present(normalized, "transmission_range_m", transmission_range)

    audio_min = _positive_integer(metadata.get("tan_so_am_thanh_min_hz"), maximum=100000)
    audio_max = _positive_integer(metadata.get("tan_so_am_thanh_max_hz"), maximum=100000)
    if (
        "dải tần âm thanh bất thường" not in source_warning.casefold()
        and audio_min is not None
        and audio_max is not None
        and audio_min <= audio_max
    ):
        normalized["audio_frequency_min_hz"] = audio_min
        normalized["audio_frequency_max_hz"] = audio_max
    elif audio_min is not None or audio_max is not None:
        flags.append("ignored_unsafe_audio_frequency")

    _set_if_present(normalized, "max_spl_db", _positive_integer(metadata.get("spl_db"), maximum=250))
    _set_if_present(
        normalized,
        "total_weight_g",
        _positive_number(metadata.get("tong_khoi_luong_cac_bo_phan_g"), maximum=10000),
    )
    year = _positive_integer(
        metadata.get("nam_san_xuat_chuan") or metadata.get("Năm sản xuất"),
        maximum=2100,
    )
    if year is not None and year >= 1900:
        normalized["manufacture_year"] = year
    _set_if_present(normalized, "origin", _clean(metadata.get("Sản xuất tại")))
    if flags:
        normalized["data_quality_flags"] = list(dict.fromkeys(flags))
    normalized["category_scope"] = "phone_recording_microphone"
    return normalized


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    data = json.loads(INPUT_FILE.read_text(encoding="utf-8-sig"))
    if not isinstance(data, list) or not data:
        raise ValueError("Không có dữ liệu micro thu âm đã xử lý")
    for item in data:
        metadata = item.get("metadata")
        if not isinstance(metadata, dict):
            raise ValueError("Sản phẩm thiếu metadata")
        item["metadata"] = normalize_metadata(metadata)
    OUTPUT_FILE.write_text(
        json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"Đã chuẩn hóa metadata cho {len(data)} sản phẩm -> {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
